---
features:
  - |
    Support is added to the os_nova ansible role to deploy resource provider
    config files to nova compute nodes. This allows automatic configuraion
    of resource providers without having to use the openstack API or
    command line.
