---
component_skel:
  cloudkitty_api:
    belongs_to:
      - cloudkitty_all
  cloudkitty_engine:
    belongs_to:
      - cloudkitty_all

container_skel:
  cloudkitty_container:
    belongs_to:
      - rating_containers
    contains:
      - cloudkitty_api
      - cloudkitty_engine

physical_skel:
  rating_containers:
    belongs_to:
      - all_containers
  rating_hosts:
    belongs_to:
      - hosts
