---

component_skel:
  zookeeper:
    belongs_to:
      - zookeeper_all

container_skel:
  zookeeper_container:
    belongs_to:
      - coordination_containers
    contains:
      - zookeeper

physical_skel:
  coordination_containers:
    belongs_to:
      - all_containers
  coordination_hosts:
    belongs_to:
      - hosts
