- name: Run tests
  hosts: all[0]
  vars_files:
    - "{{ zuul.executor.work_root }}/osa-gate-scenario.yml"
  tasks:
    - name: Run gate-check-commit.sh script # noqa: no-changed-when
      become: true
      become_user: root
      ansible.builtin.shell: >-
        scripts/gate-check-commit.sh
        {{ scenario | quote }}
        {{ action | quote }}
        {{ install_method | quote }}
      args:
        chdir: "src/opendev.org/openstack/openstack-ansible"
        executable: /bin/bash
      vars:
        skip_bootstrap:
          # NOTE(logan): ARA is already installed in the gate environment by the
          # pre-osa-aio pre-run playbook
          SETUP_ARA: False # noqa: yaml[truthy]
          # NOTE(logan): The project is bootstrapped in the pre playbook so the
          # bootstrapping can be skipped here
          SKIP_OSA_RUNTIME_VENV_BUILD: 1
          SKIP_OSA_BOOTSTRAP_AIO: 1
          SKIP_OSA_ROLE_CLONE: 1
        run_bootstrap:
          # NOTE(jrosser)
          # ZUUL_SRC_PATH is needed for bootstrap-ansible inside gate-check-commit.sh
          # when pre playbook bootstrap is disabled
          ZUUL_SRC_PATH: "{{ ansible_user_dir }}/src"
      environment: "{{ (osa_pre_run_bootstrap | default(True)) | ternary(skip_bootstrap, run_bootstrap) }}"
