---
dependency:
  name: galaxy
  options:
    requirements-file: ansible-collection-requirements.yml
    force: true

driver:
  name: docker

platforms:
  - name: "integrated-${MOLECULE_SCENARIO_NAME}"
    image: "${DOCKER_REGISTRY:-quay.io/gotmax23}/${DOCKER_IMAGE_TAG:-debian-systemd:bookworm}"
    command: ${DOCKER_COMMAND:-""}
    pre_build_image: true
    privileged: true
    systemd: true

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  config_options:
    defaults:
      inject_facts_as_vars: false

scenario:
  name: default
